server:
    port: 2000
spring:
    kafka:
        bootstrap-servers: 103.56.157.225:9092
        consumer:
            auto-offset-reset: latest
            group-id: group_id
            properties: {spring: {json: {trusted: {packages: me.hanv.tool}}}}
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
cloud:
    topic:
        login:
          request: login-request
          response: login-response
        charge:
          request: charge-request
          response: charge-response
        change-ip:
          request: change-ip-request
          response: change-ip-response
